---
title: "HOW TO USE"
---

---

Interested persons may download the pictures provided the source is acknowledged and the license agreement, [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/), is adhered to when used.  

“You are free to:

- Share — copy and redistribute the material in any medium or format
- Adapt — remix, transform, and build upon the material for any purpose, even commercially.

Under the following terms:

- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.”

**Here is an example of the citation required:**

>Pretorius, Z.A. Bender, C.M., and Boshoff, W.H.P. 2023. The Repository of South African Plant Rust Images. Available at: DOI 10.17605/OSF.IO/UGJ8Z




### Image Collection Data

---


 | **Pathogen**                          	| **Date**     	| **Collection site**                   	| **Host(s) scientific name**                                                   	| **Common name**                           	| **PREM no**            	|
|-----------------------------------------------------------	|-----------------------------	|---------------------------------------	|-------------------------------------------------------------------------------	|-------------------------------------------	|------------------------	|
| _Austropuccinia psidii_               	| 2021, 2023   	| Hermanus and Somerset West            	| _Myrtus communis_                                                             	| Common myrtle                             	|                        	|
| _Coleosporium plumeriae_              	| 2022         	| Pretoria, Gqeberha                    	| _Plumeria rubra_                                                              	| Frangipani                                	| PREM63333              	|
| _Endophyllum osteospermi_             	| 2021         	| Sandbaai                              	| _Osteospermum moniliferum_                                                    	| Bietou                                    	|                        	|
| _Kuehnola uridinis_                   	| 2023         	| Sanddrif                              	| _Rubus fruticosus_                                                            	| Wild blackberry                           	|                        	|
| _Melampsora larici-populina_          	| 2018 to 2023 	| Onrusrivier                           	| _Populus simonii, P. nigra, P. ex canescens_                                  	| Simon poplar, black poplar, grey poplar   	| PREM63318, PREM63319   	|
| _Phakopsora nishidana_                	| 2020 to 2022 	| Napier, Onrus, Somerset West, Vermont 	| _Ficus carica, F. pumila_                                                     	| Edible fig, tickey creeper                	| PREM63073              	|
| _Phakopsora pachyrhizi_               	| 2001 to 2007 	| Vryheid, Cedara, Sudwala Caves        	| _Glycine max, _                                                               	| Soybean, Kudzu                            	|                        	|
| _Phragmidium fragariae_               	| 2022 , 2023  	| Stellenbosch                          	| _Duchesnea indica_                                                            	| Wild strawberry                           	|                        	|
| _Phragmidium mucronatum_              	| 2022         	| Keurboomstrand                        	| _Rosa spp._                                                                   	| Rose                                      	| PREM63334              	|
| _Puccinia antherrini_                 	| 2022         	| Bloemfontein                          	| _Anthirrhinum majus_                                                          	| Snapdragon                                	|                        	|
| _Puccinia coronata f. sp. avenae_     	| 2020 to 2023 	| Napier, Onrus, Paarl +                	| _Avena sativa, A. fatua_                                                      	| Oat                                       	| PREM63331              	|
| _Puccinia dehiscens_                  	| 2020         	| Plettenberg Bay                       	| _Aristea ecklonii_                                                            	| Blue stars                                	| PREM63321              	|
| _Puccinia digitariae_                 	| 2010 to 2021 	| Bloemfontein, Glen                    	| _Solanum campylacanthum, S. lichtensteinii, S. melongena, Digitaria eriantha_ 	| Bitter apple, eggplant, Smuts fingergrass 	| PREM63072, PREM63074,  	|
| _Puccinia doidgeae_                   	| 2023         	| Onrus                                 	| _Cyperus polystacheos_                                                        	| Sedge                                     	|                        	|
| _Puccinia graminis f. sp. avenae_     	| 2021         	| Greytown                              	| _Avena sativa_                                                                	| Oat                                       	| PREM63329              	|
| _Puccinia graminis f. sp. tritici_    	| 2021         	| Greytown, Paarl                       	| _Triticum aestivum, Hordeum vulgare, X triticosecale_                         	| Bread wheat, Barley, Triticale            	| PREM63328              	|
| _Puccinia granularis_                 	| 2022         	| Onrus                                 	| _Pelargonium cucullatum_                                                      	| Pelargonium                               	|                        	|
| _Puccinia helianthi_                  	| 2022         	| Paarl                                 	| _Helianthus annuus_                                                           	| Sunflower                                 	|                        	|
| _Puccinia hemerocallidis_             	| 2021         	| Paarl                                 	| _Hemerocallis sp._                                                            	| Daylily                                   	| PREM63323              	|
| _Puccinia hordei_                     	| 2021         	| Napier                                	| _Hordeum vulgare_                                                             	| Barley                                    	| PREM63330              	|
| _Puccinia lagenophorae_               	| 2018 to 2021 	| Onrus, Hermanus                       	| _Senecio halimifolius, Cineraria geifolia, Arctotheca populifolia_            	| Tabakbos, Cinerarea, Sea pumpkin          	|                        	|
| _Puccinia malvacearum_                	| 2021 to 2022 	| Onrus, Paarl, Bloemfontein            	| _Malva parviflora, Alcea rosea_                                               	| Mallow, Hollyhock                         	|                        	|
| _Puccinia menthae_                    	| 2023         	| Onrus                                 	| _Mentha spicata_                                                              	| Spearmint                                 	|                        	|
| _Puccinia pelargonii-zonalis _        	| 2019 to 2021 	| Onrusrivier                           	| _Pelargonium x hortorum_                                                      	| Ornamental geranium                       	| PREM63324              	|
| _Puccinia polycampta_                 	| 2021         	| Hermanus                              	| _Trachyandra ciliata_                                                         	| Veldkool                                  	|                        	|
| _Puccinia polypogonis_                	| 2022         	| Onrus                                 	| _Polypogon monspeliensis_                                                     	| Annual beard grass                        	|                        	|
| _Puccinia porri_                      	| 2021 to 2022 	| Elim, Bloemfontein                    	| _Allium fistolosum, A. sativum_                                               	| Bunching onion, garlic                    	| PREM63322              	|
| _Puccinia sorghi_                     	| 2021 to 2022 	| Ugie                                  	| _Zea mays_                                                                    	| Maize                                     	|                        	|
| _Puccinia stenotaphri_                	| 2022         	| Vermont                               	| _Stenotaphrum secundatum_                                                     	| St Augustine (buffalo) grass              	| PREM63326              	|
| _Puccinia striiformis f. sp. tritici_ 	| 2022         	| Greytown, Bloemfontein, Napier        	| _Triticum aestivum_                                                           	| Bread wheat                               	|                        	|
| _Puccinia tanaceti_                   	| 2022         	| Hermanus                              	| _Argyranthemum frutescens_                                                    	| Marguerite daisy                          	| PREM63325              	|
| _Puccinia taraxaci_                   	| 2023         	| Onrus                                 	| _Taraxum officinale_                                                          	| Dandelion                                 	|                        	|
| _Puccinia thaliae_                    	| 2022         	| Bosbokstrand                          	| _Canna indica_                                                                	| Canna                                     	|                        	|
| _Puccinia triticina_                  	| 2021         	| Napier                                	| _Triticum aestivum_                                                           	| Bread wheat                               	| PREM63327              	|
| _Tranzschelia discolor_               	| 2021 to 2023 	| Paarl, Ladybrand, Bloemfontein        	| _Prunus persica, P. armeniaca_                                                	| Peach, apricot                            	|                        	|
| _Uromyces albucae_                    	| 2022         	| Gouritzmond                           	| _Ornithogalum canadense_                                                      	| Snotui                                    	|                        	|
| _Uromyces aloes_                      	| 2019, 2022   	| Onrus, Paarl                          	| _Aloe sp._                                                                    	| Ornamental aloe                           	|                        	|
| _Uromyces appendiculatus_             	| 2022         	| Bloemfontein                          	| _Phaseolus vulgaris_                                                          	| Drybean                                   	|                        	|
| _Uromyces badius_                     	| 2022         	| Hawston                               	| _Haemanthus coccineus_                                                        	| Paintbrush lily                           	|                        	|
| _Uromyces dianthi_                    	| 2022         	| Bloemfontein                          	| _Dianthus chinensis_                                                          	| Grasangelier                              	|                        	|
| _Uromyces ixiae_                      	| 2021         	| Hermanus                              	| _Gladiolus cunonius_                                                          	| Gladiolus                                 	|                        	|
| _Uromyces kentaniensis_               	| 2018 to 2021 	| Onrusrivier                           	| _Chasmanthe aethiopica_                                                       	| Cobra lily                                	| PREM63320              	|
| _Uromyces rumicis_                    	| 2023         	| Onrus                                 	| _Rumex crispus_                                                               	| Curly dock                                	|                        	|

---

_*Disclaimer: Using available resources, every effort has been made to accurately identify the rust pathogen/s and their host plant/s.  Authors, contributors and curators can not be held responsible for the use by other parties of the information in the repository._

